### PR TITLE
Updated Action Translator

### LINKED ISSUE #25: Update action translator
Update and clean up action translator. Actions should match those available to the fourth year project team.

### PR DESCRIPTION
**Pull request by Simon-Yacoub**
Removed old code for previous version. Added code for new version. Please review and let me know if any changes are needed.

### CODE REVIEW

**Comment by pgavigan** [comment]
A few comments:

- Please remove any pyc files from the repos
- Please update the launch file to include all sensor nodes, the perception translator and the action translator
- Action format needs to follow a similar format as the perceptions, with a term followed by one or several terms in brackets.
- Docking and undocking actions: station(dock), station(undock)
- Movement actions: drive(forward), drive(backward) and so on. It needs to be clearer what the difference is between the different actions. What is the use of sright, bleft, sleft, avoidright, and so on?

**Comment by pgavigan** [comment]
I just thought of something else to add to the actions. It might be a good idea to have an action that allows direct setting of the twist messages. I think the message would be of the format: drive(X,Z), where X and Z are the parameters for a twist message.

**Comment by Simon-Yacoub** [comment]
Ok, I will work on it!

**Comment by Simon-Yacoub** [comment]
> * Action format needs to follow a similar format as the perceptions, with a term followed by one or several terms in brackets.
> * Docking and undocking actions: station(dock), station(undock)

when you say action format needs to follow a similar format as the perceptions, do you mean that the Agent will publish statements like drive(forward), station(dock)... and I will have to parse the information from the actions topics better?

**Comment by pgavigan** [comment]
The short answer is yes. The action format always needs to have a term with
other terms in brackets.

I'm also thinking I may want to have the agent specify the twist message,
at least the x and z parameters, itself. In this case the action would be
something like "drive(x,z)" or something like that.
--
Patrick

**Comment by Simon-Yacoub** [comment]
Ok, thank you for clarifying.

**Pull request closed without merging**
