### PR TITLE
Battery

### LINKED ISSUE #19: BatterySensor
Add battery sensor

### PR DESCRIPTION
**Pull request by Simon-Yacoub**
The battery branch adds the battery sensor which will be used by the perception translator

### CODE REVIEW

**Comment by Simon-Yacoub** [comment]
The reason I would like to add the battery sensor and not a battery perception translator is that I would prefer to have one perception translator.

**Comment by pgavigan** [comment]
> The reason I would like to add the battery sensor and not a battery perception translator is that I would prefer to have one perception translator.

I agree that there should only be one perception translator, however the battery sensor data is already published to ROS by create_autonomy. The role of the sensor nodes is to get the sensor data from some sensor and provide it to ROS. In the case of the battery, this role is filled by the create_autonomy node. The perception translator can subscribe to the charge ratio topic (as this node does) and then simply publish battery(ChargeRatio) to perceptions along with the other perceptions that have been translated. There isn't any need for this node if the perception translator does that. This node only adds another hop to the process, only adding latency to the system.

**Comment by Simon-Yacoub** [comment]
Yeah I understand what you mean now. In that case I will remove the BatterySensor.py and instead just put the code into perception Translator.

**Comment by pgavigan** [comment]
> Yeah I understand what you mean now. In that case I will remove the BatterySensor.py and instead just put the code into perception Translator.

Thanks, I think that will make for a simpler system in the end.

**Pull request merged**
